name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
    - run: cargo build --target x86_64-pc-windows-gnu --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/x86_64-pc-windows-gnu/release/weylus.exe
       
